name: 'Build and push action'
description: 'Creates images and pushes them to the given registry. Requires image repository credentials to push.'
inputs:
  container-registry-url:
    description: 'URL for the container registry'
    required: true
    default: ''
  container-registry-username:
    description: 'Username for the container registry'
    required: true
    default: ''
  container-registry-password:
    description: 'Password for the container registry'
    required: true
    default: ''
  container-repository-name:
    description: 'The name of the container repository (middle part of the image tag)'
    required: true
    default: ''
  dockerfile-path:
    description: 'Path to the Dockerfile'
    required: true
    default: ''
  docker-build-context:
    description: 'The build context for the docker build'
    required: false
    default: '.'
  docker-build-args:
    description: 'Additional build arguments for the docker build'
    required: false
    default: ''
  docker-image-name:
    description: 'The name of the image'
    required: true
    default: ''
  kube-config-base64:
    description: 'The base64 encoded kubeconfig needed to connect to the cluster'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ inputs.container-registry-url }}
        username: ${{ inputs.container-registry-username }}
        password: ${{ inputs.container-registry-password }}

    - name: Build and push
      if: inputs.container-registry-url != '' && inputs.container-registry-username != '' && inputs.container-registry-password != ''
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ${{ inputs.docker-build-context }}
        file: ${{ inputs.dockerfile-path }}
        build-args: ${{ inputs.docker-build-args }}
        tags: ${{ inputs.container-registry-url }}/${{ inputs.container-repository-name }}/${{ inputs.docker-image-name }}:${{ github.sha }}-${{ github.run_id }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create kubeconfig file
      run: echo ${{ inputs.kube-config-base64 }} | base64 -d > kubeconfig.yml
      shell: bash

    - name: Fetch kubectl
      run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      shell: bash

    - name: Check if configmap exists
      id: check-configmap
      run: kubectl --kubeconfig=kubeconfig.yml get configmap cd-versions -o json
      shell: bash
      continue-on-error: true

    - name: Create configMap if not exists
      if: steps.check-configmap.outcome == 'failure'
      run: kubectl --kubeconfig=kubeconfig.yml create configmap cd-versions --from-literal=${{ inputs.docker-image-name }}=${{ github.sha }}-${{ github.run_id }}
      shell: bash

    - name: Update existing configmap
      if: steps.check-configmap.outcome == 'success'
      run: |
        kubectl --kubeconfig=kubeconfig.yml patch cm cd-versions --type json --patch '[{ "op": "replace", "path": "/data/${{ inputs.docker-image-name }}", "value": "${{ github.sha }}-${{ github.run_id }}" }]'
      shell: bash
